export const LOTTERY_LIST = [
    {
        id: 0,
        name: "ALADDIN",
        url: "https://lottery.broadwaydirect.com/show/aladdin/",
        img: "assets/bway/aladdin.jpg",
        theater: "NEW AMSTERDAM THEATRE",
    },
    {
        id: 1,
        name: "DEATH BECOMES HER",
        url: "https://lottery.broadwaydirect.com/show/dbh-nyc/",
        img: "assets/bway/dbh-nyc.jpg",
        theater: "LUNT-FONTANNE THEATRE",
    },
    {
        id: 2,
        name: "ELF THE MUSICAL",
        url: "https://lottery.broadwaydirect.com/show/elf-ny/",
        img: "assets/bway/elf-ny.jpg",
        theater: "MARQUIS THEATRE",
    },
    {
        id: 3,
        name: "MJ",
        url: "https://lottery.broadwaydirect.com/show/mj-ny/",
        img: "assets/bway/mj-ny.jpg",
        theater: "NEIL SIMON THEATRE",
    },
    {
        id: 4,
        name: "SIX",
        url: "https://lottery.broadwaydirect.com/show/six-ny/",
        img: "assets/bway/six-ny.jpg",
        theater: "LENA HORNE THEATRE",
    },
    {
        id: 5,
        name: "THE LION KING ",
        url: "https://lottery.broadwaydirect.com/show/the-lion-king/",
        img: "assets/bway/the-lion-king.jpg",
        theater: "MINSKOFF THEATRE",
    },
    {
        id: 6,
        name: "WICKED",
        url: "https://lottery.broadwaydirect.com/show/wicked/",
        img: "assets/bway/wicked.jpg",
        theater: "GERSHWIN THEATRE",
    },
];
